global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: "qdrant"
    static_configs:
      - targets: [qudrant:6333]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: [localhost:9090]

  - job_name: "node-exporter"
    static_configs:
      - targets: [node-exporter:9100]

  - job_name: "fastapi"
    static_configs:
      - targets: [fastapi:8000]
    metrics_path: "/TrhBVe_m5gg2002_E5VVqS"